version: "3"
services:
  clientfluent:
    image: fluent/fluentd
    volumes:
      - ./client_fluentd.conf:fluentd/etc/fluent.conf
    ports: 
      - 24224:24224
  serverfluent:
    image: fluent/fluentd
    volumes:
      - ./server_fluentd.conf:fluentd/etc/fluent.conf
